---
title: "DSAIDE Package"
author: "Andreas Handel"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{DSAIDE}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---



This is the future home of an introductory tutorial to the DSAIDE pacakage



## Introduction



The `html_vignette` template includes a basic CSS theme. To override this theme you can specify your own CSS in the document metadata as follows:

    output: 
      rmarkdown::html_vignette:
          css: mystyles.css




##Use options for end users


###Interactive use through the Shiny user interface

This is the main intended use of this package.
Start the main menu of the package by calling dsaidemenu(). 
Pick a shiny app corresponding to a model, and explore the model through the corresponding shiny UI. The UI contains information about the model and a list of tasks to try. 


###Supplementing simulations with custom code
Call each simulator function directly from the R console, without going
  through the shiny app. Each model simulator function is called simulate_XXX
  and is documented. See the documentation for the package to find the names
  of the different simulation functions, or check the 'further information' 
  tab for a given shiny app. 
  You can call the functions with different initial condition and parameter values. 
  This allows you to for instance write a few
  lines of extra R code to loop over some model parameter, instead of the manual setting
  through the sliders in the shiny app. This gives you
  some more flexibility in what you can do with these functions, but requires
  being able to write a little bit of R code.

###Modifying simulations
Find the code for a simulator function you are interested in and modify
  it to your needs. This provides the most flexibility in what you can do with 
  this package, and you can end up with any model you need, 
  but for that you need to know or learn some
  more R coding. To make it easy to get the source code for the simulator functions,
  they are located in a subdirectory called 'simulatorfunction' inside the DSAIDE 
  package folder.




##Use options for developers



