---
title: "ID modeling related resources"
date: "1/27/2020"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Other resources}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Overview

A list of resources broadly related to the DSAIDE package and infectious disease modeling (in R).
These are resources I'm aware of, many others like exist. Let me know if I'm missing anything.

**Currently very incomplete, just started to add materials. Until I get around to adding more here, see Sam Abbott's list (see below).**

# Other packages by our group

* A 'companion' package to DSAIDE, called Dynamical Systems Approaches for Immune Respone Modeling (DSAIRM), focuses on models for analyzing with-host infection dynamics. It has the same structure as DSAIDE. [See the DSAIRM site for more information.](https://ahgroup.github.io/DSAIRM)

* A new package (not yet on CRAN) called `modelbuilder` lets you build and analyze your own compartmental models (ODE, discrete time or stochastic) without having to write code. The package should be working but it's still in development and some functionality is not there. Check it out and use at your own risk [here](https://ahgroup.github.io/modelbuilder/).

# ID modeling R packages

* [idmodelr](https://www.samabbott.co.uk/idmodelr/) by Sam Abbott. Many basic compartmental (SIR type) models, a little bit of coding is required. He also has [a list of related resources](https://www.samabbott.co.uk/idmodelr/articles/resources.html), which - not surprisingly - has a lot of overlap with the information on this page.

* [shinySIR](https://github.com/SineadMorris/shinySIR) by Sinead Morris. Exploration of several SIR-type models through Shiny. Doesn't have the documentation of DSAIDE, but has some models not in DSAIDE.

* [Epimodel](https://www.epimodel.org/)

# ID modeling books

To come

# ID modeling courses

To come

# ID modeling websites

[epirecipes](http://epirecip.es/) - a cookbook of ID epi models.
