---
title: VectorTemp
output:
  html_document:
    theme: null
    highlight: null
    fig_caption: true
    mathjax: default 
    keep_md: false
---

## Overview {#shinytab1}
This model explores the effects of global warming on a vector-borne disease.  

### Learning Objectives
* Understand the ways changes in temperature can affect disease dynamics

## The Model {#shinytab2}

### Model Overview
The main model is similar to the one discussed in the _Vector Transmission_ app. Two species, hosts and vectors, are tracked, using the basic SIR framework. The model has the following compartments:  

* **Sh** - uninfected and susceptible host 
* **Ih** - infected/infectious hosts
* **Rh** - recovered/removed hosts
* **Sv** - susceptible vectors
* **Iv** - infected/infectious vectors

We assume that once vectors are infected, they stays infected until death. Therefore, recovered vectors are not included in the model.

The processes being modeled are:

* Susceptible hosts can become infected by contact with infected vectors at rate _b~1~_. 
* Susceptible vectors can become infected by contact with infected hosts at rate _b~2~_. 
* Infected hosts recover after some time at rate _g_. 
* Recovered hosts lose their immunity at rate _w_.
* New susceptible vectors are born at a rate _m_. Births are reduced as the vectors reach carrying capacity _V~m~_.
* Susceptible and infected vectors die at rate _n_. The inverse of this rate is the average lifespan. 

We envision hosts to be humans and vectors to be e.g. mosquitoes. We further assume the time scale for the model is short enough that we can ignore births and deaths for human hosts but not vectors. This is likely a decent approximation as long as our simulation time is only a few years.


### Model Diagram
The flow diagram for the model is


### Model Equations
The equations for the model are:

$$\dot S_h = - b_1 S_h I_v + w R_h$$ 
$$\dot I_h = b_1 S_h I_v  - g I_h$$ 
$$\dot R_h = g I_h - w R_h$$
$$\dot S_v =m(1-\frac{S_v + I_v}{V_m})(S_v+I_v) - b_2 S_v I_h - n S_v$$ 
$$\dot I_v = b_2 S_v I_h  - n I_v$$ 

### Temperature
The main focus of this model is to study the impact of temperature on disease dynamics. To do so, we expliclity model temperature. We designate temperature by **W**. Temperature is not modeled as a differential equation, instead it is directly a time-dependent variable. Specifically, we model temperature with this equation:

$$W =  w_0 + (1 + w_3t/T)w_1 sin(2 \pi t/T) + w_2 t/T$$

* _w0_ is some base average temperature.
* The seasonal variation in temperature is designated _w1_.
* A linear increase with time in average base temperature caused by global warming is designated _w2_.
* An increase in extreme temperature events with time (stronger seasonal variation) caused by global warming is designated _w3_.
*  The parameter T is set depending on the time units chosen for the model. For example if you want to run the model in units of days, the underlying simulation code will set T=365, similarly, for weeks it will be T=52. This ensures that the seasonal variation always has a period of a year.

The impact of temperature on the dynamics is modeled as follows:
* As temperature increases, the birth rate of vectors increases linearly, i.e. we set m=m_w*W 

resulting in an increasing number of susceptible vectors up to a certain temperature. At a defined temperature, the birth rate equals the death rate. Above this temperature death rate exceeds birth rate causing the vector population to decline. 






## What to do {#shinytab3}

Keep in mind all time units are in months. If tmax is set to 1000 it is 1000 months and therefore approximately 83.33 years.

MODEL IS DIFFERENT THAN ORIGINAL, NONE OF TASKS WORK JUST NOW.

### Task 1
  * Set the model parameters accordingly
    * 1000 initially susceptible for both hosts and vectors with 1 infected host and no infected vectors.
    * Set b2 = 0.003 and b1 = 0
    * Set w = 0.5 and g = 0.1
    * Set m0 = 0.1 = n
    * Set tmax = 100
  * Run the simulation. Is there an outbreak?
  * Now change b1 = b2. Run the simulation. Is there an outbreak? Is the disease eliminated from the population? You should see the disease become endemic
  * Now change infected hosts to 0 and begin with 1 infected vector. Is there an outbreak? Does anything change? Why or why not? Over the past 2 simulations, what have you noticed about the susceptible host population? Does it reach 0? Why or why not? What about the vector poulation?
  * Play with b1 and b2 and explore the vector transmission dynamics.
  
### Task 2
  * Focus on the weather graph and the vector population. Set infected vectors to 0, the starting temperature (W0) to 25, seasonal variation(W1) to 2,and tmax to 1000. What does this varriation mean for temperature in words? What do you expect the graph of the temperature to look like? What is happening to the vector population?
 * Change the W0 to 23.5, W1 to 5 and global warming: linear (W2) to 1 and run the simulation. How do you expect the temperature to change over time? What effect does this have on the vector and host populations? What is happening to the vector population?
  * Change the global warming: extremes (W3) to 0.5 and tmax to 2000 and run the simulation. How do you expect the temperature to change over time given values in W0, W1, W2 and W3? What do you expect to happen to the vector population?
  * Look at the equations for the vector populations. What do you notice about the birth rates? With this in mind, what do you expect the vector population graph to look like when p = 10, what about when p = 40?
  * At the end of this task you should have come to the conclusion that W1 acts as a linear temperature multiplier. It can be thought of as a slope. W2 acts to model the seasonal changes in temperature creating a sinusoidal model that increases and decreases with changing time. W3 acts to create more extreme temperature events. Global warming is expected to create higher highs and lower lows. W3 acts to mimic (very simply) this effect. The other thing that should have been noticed is that the vectors grow better at lower temperatures. The vector population continues to grow until temperature p where the death rate becomes larger than the birth rate.

### Task 3
  * Change infected hosts and vectors to 0, w = 0.01, b1 = 0.0001, b2 = 0.0001, g = 0.01, m0 = 0.01, m1 = 0, n = 0.01 and tmax to be 2000. Leave all other parameters similar to task 1. Now change the starting temperature (W0) to 23.5. W1 to 2 and W3 to 0.1 and run the simulation. At what temperature does the vector population peak? What do we know about the birth and death rate at this temperature? At what temperarure does the population growth rate = 0?
  * Now change the number of infected vectors to 1. Does this change the population dynamics? Is there an outbreak?
  * Play arround with the starting temperature as well as teperature variations to see how it affects the population dynamics of vectors.
  
### Task 4
  * Now change the settings to be similar to the end of task 2. 1000 sussceptible hosts and vectors with one infected vector, tmax = 2000, b1 = 0.001, b2 = 0.001, w = 0.5, g = 0.1, W0 = 22, W1 = 5, W2 = 1, W3 = 0.5. Does an outbreak occur? What do you notice about the begining of the graph?
  * Now change the starting temperature (W0) to 23.5 and run the model. Do you notice any pattern between the 3 graphs? Is there a relationship between W and Sv or Iv? What about W and SH?
  * Change W0 back to 22 and then change W2 to 2. How do you expect this to differ from the initial outbreak seen the first step of task 4?
  * Play arround with p, W0, W1, W2, W3 to see how they affect the outbreak.
  
### Task 5
* Look at the vector graphs generatied in the last task. Why are all the vectors not infected? Under what scenario would Sv go to 0?
* Now lets assume that there is transovarial transmission. Change the m0 to 0 and m1 to 0.01 and run the simulation. What would you expect the graph to look like? What is happening in words? Why does Sv go down to zero?
* What assumptions are made in the expression of trans-ovarial transmission above?

## Further Information {#shinytab4}

For this app, the underlying function running the simulation is called simulate_vectortemptest2.R. You can call this function directly, without going through the shiny app.

A key limitation of this model is the lack of births and deaths in the host population. This was left out for simplicity but it has the added benefit of allowing users to more easily identify outbreaks caused by vectors as well as the effects of waning immunity over the long term


### References
