---
title: App/Module Name - Practice
output:
  html_document:
    theme: null
    highlight: null
    fig_caption: true
    mathjax: default 
    keep_md: false
---


```{r}
################
#This R chunk only exists as an easy way to add comments - a bit trickier in Markdown itself
################
#You can adjust settings in the YAML header for styling 
#first make sure your simulator function is in the \R folder 
#and your App is in an appropriately named folder inside \shinyapps
#use this template and fill it with information for your App
#turn this into an HTML file using RMarkdown (knitr/pandoc)
#make sure the HTML file is in the directory with all the App documentation
#run the processing script (processAllFiles.R), which processes all documentation
#if everything works, the information described below should automatically be displayed in tabs at the bottom of the App UI
#note that the processing script changes some of the styling as specified in the shinystyle.css file
```

##Overview {#shinytab1}
Everything inside sections called shinytab will be processed by the R script and placed in separate tabs at the bottom of the shiny UI. Anything not in such a section will be ignored.
The general structure and headings are as given here.

In this tab, provide a quick overview and most important information.

##The Model {#shinytab2}

###Model Overview
Describe the model underlying the App.

###Model Implementation
Could have an extra section here showing flow diagram and equations, if applicable.


##What to do {#shinytab3}

###Task 1: 
* Describe the different tasks a user should do

###Task 2: 
* Another task to be done


##Answers 
This section does not have the shinytab label and is therefore ignored and not included in the app. One could provide the answers here. Note that if this file is supplied with the package, the answers are in principle available, so most users might not know where/how to look.

###Answer 1: 
Answer to task 1.

##Further Information {#shinytab4}
* This gives information for anyone wanting to dig deeper. 
* Could be list of references, or explanation on how to access the underlying code, etc.

##More sections
Any other sections that don't have the _shinytab_ label can be included here but are ignored by the processing script and not included in the app UI.
