#' SIR model
#' 
#' A basic SIR model with 3 compartments and infection and recovery processes
#' 
#' @description USER CAN ADD MORE DETAILS HERE 
#' @param S starting value for Susceptible
#' @param I starting value for Infected
#' @param R starting value for Recovered
#' @param b infection rate
#' @param g recovery rate
#' @param tstart Start time of simulation
#' @param tfinal Final time of simulation
#' @param dt Time step
#' @return The function returns the output as a list. 
#' The time-series from the simulation is returned as a dataframe saved as list element ts. 
#' The ts dataframe has one column per compartment/variable. The first column is time.   
#' @details USER CAN ADD MORE DETAILS HERE  
#' @examples  
#' # To run the simulation with default parameters just call the function:  
#' result <- simulate_IDdynamicsintroNew_desolve() 
#' @section Warning: This function does not perform any error checking. So if you try to do something nonsensical (e.g. have negative values for parameters), the code will likely abort with an error message
#' @section Model Author: Andreas Handel
#' @section Model creation date: 2018-09-04
#' @section Function Author: generated by convert_to_desolve function 
#' @section Function creation date: 2018-09-07
#' @export 

simulate_IDdynamicsintroNew_desolve <- function(vars = c(S = 1000, I = 1, R = 0), pars = c(b = 0.002, g = 1), time = c(tstart = 0, tfinal = 100, dt = 0.1) ) 
{ 
  #Block of ODE equations for deSolve 
  SIR_model_ode <- function(t, y, parms) 
  {
    with( as.list(c(y,parms)), { #lets us access variables and parameters stored in y and parms by name 
      #StartODES
      #Susceptible : infection of susceptibles :
      dS = -b*S*I
      #Infected : infection of susceptibles : recovery of infected :
      dI = +b*S*I -g*I
      #Recovered : recovery of infected :
      dR = +g*I
      #EndODES
      list(c(dS,dI,dR)) 
    } ) } #close with statement, end ODE code block 
  
  #Main function code block 
  times=seq(time[1],time[2],by=time[3]) 
  odeout = deSolve::ode(y = vars, parms= pars, times = times,  func = SIR_model_ode) 
  result <- list() 
  result$ts <- as.data.frame(odeout) 
  return(result) 
} 
