#' Environmental Transmission model
#' 
#' An SIR model including environmental transmission
#' 
#' @details The model includes susceptible, infected, and environmental compartments. 
#' @param vars vector of starting conditions for model variables: 
#' \itemize{ 
#' \item S : starting value for Susceptible
#' \item I : starting value for Infected
#' \item R : starting value for Recovered
#' \item E : starting value for Environmental Pathogen
#' } 
#' @param pars vector of values for model parameters: 
#' \itemize{ 
#' \item bd : direct transmission rate
#' \item be : environmental transmission rate
#' \item m : births
#' \item n : natural deaths
#' \item g : recovery rate
#' \item p : shedding rate
#' \item c : decay rate
#' } 
#' @param times vector of values for model times: 
#' \itemize{ 
#' \item tstart : Start time of simulation
#' \item tfinal : Final time of simulation
#' \item dt : Time step
#' } 
#' @return The function returns the output as a list. 
#' The time-series from the simulation is returned as a dataframe saved as list element \code{ts}. 
#' The \code{ts} dataframe has one column per compartment/variable. The first column is time.   
#' @examples  
#' # To run the simulation with default parameters:  
#' result <- simulate_Environmental_Transmission_model_ode() 
#' @section Warning: This function does not perform any error checking. So if you try to do something nonsensical (e.g. have negative values for parameters), the code will likely abort with an error message.
#' @section Model Author: Andreas Handel
#' @section Model creation date: 2018-09-14
#' @section Code Author: generated by the \code{generate_ode} function 
#' @section Code creation date: 2018-09-14
#' @export 
 
simulate_Environmental_Transmission_model_ode <- function(vars = c(S = 10000, I = 1, R = 0, E = 0), pars = c(bd = 1e-04, be = 0, m = 0, n = 0, g = 0.2, p = 0, c = 10), times = c(tstart = 0, tfinal = 100, dt = 0.1) ) 
{ 
  #Block of ODE equations for deSolve 
  Environmental_Transmission_model_ode <- function(t, y, parms) 
  {
    with( as.list(c(y,parms)), { #lets us access variables and parameters stored in y and parms by name 
    #StartODES
    #Susceptible : births : natural death : direct infection : environmental infection :
    dS = +m -n*S -bd*I*S -be*E*S
    #Infected : direct infection : environmental infection : natural death : recovery of infected :
    dI = +bd*I*S +be*E*S -n*I -g*I
    #Recovered : natural death : recovery of infected :
    dR = -n*I +g*I
    #Environmental Pathogen : shedding by infected : decay :
    dE = +p*I +c*E
    #EndODES
    list(c(dS,dI,dR,dE)) 
  } ) } #close with statement, end ODE code block 
 
  #Main function code block 
  timevec=seq(times[1],times[2],by=times[3]) 
  odeout = deSolve::ode(y = vars, parms = pars, times = timevec,  func = Environmental_Transmission_model_ode) 
  result <- list() 
  result$ts <- as.data.frame(odeout) 
  return(result) 
} 
