#' SIR model
#' 
#' A basic SIR model with 3 compartments and infection and recovery processes
#' 
#' @details The model includes susceptible, infected, and recovered compartments. The two processes that are modeled are infection and recovery.
#' @param vars vector of starting conditions for model variables: 
#' \itemize{ 
#' \item S : starting value for Susceptible
#' \item I : starting value for Infected
#' \item R : starting value for Recovered
#' } 
#' @param pars vector of values for model parameters: 
#' \itemize{ 
#' \item b : infection rate
#' \item g : recovery rate
#' } 
#' @param times vector of values for model times: 
#' \itemize{ 
#' \item tstart : Start time of simulation
#' \item tfinal : Final time of simulation
#' \item dt : Time step
#' } 
#' @return The function returns the output as a list. 
#' The time-series from the simulation is returned as a dataframe saved as list element \code{ts}. 
#' The \code{ts} dataframe has one column per compartment/variable. The first column is time.   
#' @examples  
#' # To run the simulation with default parameters:  
#' result <- simulate_SIR_model_ode() 
#' @section Warning: This function does not perform any error checking. So if you try to do something nonsensical (e.g. have negative values for parameters), the code will likely abort with an error message.
#' @section Model Author: Andreas Handel
#' @section Model creation date: 2018-09-14
#' @section Code Author: generated by the \code{generate_ode} function 
#' @section Code creation date: 2018-09-14
#' @export 
 
simulate_SIR_model_ode <- function(vars = c(S = 1000, I = 1, R = 0), pars = c(b = 0.002, g = 1), times = c(tstart = 0, tfinal = 100, dt = 0.1) ) 
{ 
  #Block of ODE equations for deSolve 
  SIR_model_ode <- function(t, y, parms) 
  {
    with( as.list(c(y,parms)), { #lets us access variables and parameters stored in y and parms by name 
    #StartODES
    #Susceptible : infection of susceptibles :
    dS = -b*S*I
    #Infected : infection of susceptibles : recovery of infected :
    dI = +b*S*I -g*I
    #Recovered : recovery of infected :
    dR = +g*I
    #EndODES
    list(c(dS,dI,dR)) 
  } ) } #close with statement, end ODE code block 
 
  #Main function code block 
  timevec=seq(times[1],times[2],by=times[3]) 
  odeout = deSolve::ode(y = vars, parms = pars, times = timevec,  func = SIR_model_ode) 
  result <- list() 
  result$ts <- as.data.frame(odeout) 
  return(result) 
} 
